### ISSUE TITLE
Activity de adicionar contatos

### ISSUE THREAD

**Issue by iksmada** [iksmada/p2pChat#2]
criar a classe java e o xml respectivo da classe para adicionar os contatos e popular com PeerListAdapter

**Comment by iksmada** [comment]
Colocar no codigo do onCreate algo parecido com isso:
// Find ListView to populate
`ListView lvItems = (ListView) findViewById(R.id.lvItems);`
// Setup cursor adapter using cursor from last step
`PeerListAdapter peersAdapter = new PeerListAdapter(this,peers);`
// Attach cursor adapter to the ListView
`lvItems.setAdapter(peersAdapter);`

**Comment by brunowilliamsap** [comment]
xml do listview feito, falta a java
